[tools]
"1password" = "latest"
"flux2" = "latest"
"github-cli" = "latest"
"helm" = "latest"
"helmfile" = "latest"
"jq" = "latest"
"just" = "latest"
"krew" = "latest"
"kubecolor" = "latest"
"kubectl" = "latest"
"kustomize" = "latest"
"lefthook" = "latest"
"oxfmt" = "latest"
"talos" = "latest"
"vals" = "latest"
"yamlfmt" = "latest"
"yq" = "latest"
"aqua:mitsuhiko/minijinja" = "latest"
"github:home-operations/flate" = "latest"
